"""empty message

Revision ID: 13299e088001
Revises: 4d19c354182b
Create Date: 2025-12-05 18:59:30.969488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13299e088001'
down_revision = '4d19c354182b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_people_id_people_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['people_id'], ['id'])
        batch_op.drop_column('id_people')

    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_planets_id_user_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_planets_id_planet_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['planet_id'], ['id'])
        batch_op.drop_column('id_user')
        batch_op.drop_column('id_planet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_planet', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_planets_id_planet_fkey', 'planets', ['id_planet'], ['id'])
        batch_op.create_foreign_key('favorite_planets_id_user_fkey', 'user', ['id_user'], ['id'])
        batch_op.drop_column('planet_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('favorite_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_people', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_people_id_people_fkey', 'people', ['id_people'], ['id'])
        batch_op.drop_column('people_id')

    # ### end Alembic commands ###
