"""empty message

Revision ID: 4d19c354182b
Revises: 771d8dc5d3d0
Create Date: 2025-12-03 02:03:16.575011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d19c354182b'
down_revision = '771d8dc5d3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_people', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_people'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_planet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_planet'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorit_people')
    op.drop_table('favorit_planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorit_planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_planet', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_planet'], ['planets.id'], name='favorit_planets_id_planet_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='favorit_planets_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorit_planets_pkey')
    )
    op.create_table('favorit_people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_people', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_people'], ['people.id'], name='favorit_people_id_people_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorit_people_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorit_people_pkey')
    )
    op.drop_table('favorite_planets')
    op.drop_table('favorite_people')
    # ### end Alembic commands ###
