"""empty message

Revision ID: 771d8dc5d3d0
Revises: 9f2219cab387
Create Date: 2025-12-02 01:02:52.089611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771d8dc5d3d0'
down_revision = '9f2219cab387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('diameter', sa.Numeric(precision=120), nullable=False),
    sa.Column('climate', sa.String(length=100), nullable=False),
    sa.Column('population', sa.Numeric(precision=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favorit_planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_planet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_planet'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorit_planet')
    op.drop_table('planet')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=400),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    op.create_table('planet',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('planet_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('diameter', sa.NUMERIC(precision=120, scale=0), autoincrement=False, nullable=False),
    sa.Column('climate', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('population', sa.NUMERIC(precision=120, scale=0), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='planet_pkey'),
    sa.UniqueConstraint('name', name='planet_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('favorit_planet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_planet', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_planet'], ['planet.id'], name='favorit_planet_id_planet_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='favorit_planet_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorit_planet_pkey')
    )
    op.drop_table('favorit_planets')
    op.drop_table('planets')
    # ### end Alembic commands ###
